[project]
name = "tabiclsbo"
version = "0.1.0"
description = "TabICLv2 implemented by sbo"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "torch>=2.10.0",
]
[tool.ruff]
line-length = 120
[tool.ruff.lint]
ignore = ["E741"]
